version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    image: php:8.1-fpm
    volumes:
      - .:/var/www